# Generated by Django 3.1.12 on 2025-12-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20251214_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cart', 'Cart'), ('Pending', 'Pending'), ('Successful', 'Successful'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='Cart', max_length=20),
        ),
    ]
